// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzYOzWXWsXRSXnjR5i6Nr_ManXKVBcV8k',
    appId: '1:1036042599398:web:7e99c3f24e19945b4c7427',
    messagingSenderId: '1036042599398',
    projectId: 'ecommercefirebase-339fa',
    authDomain: 'ecommercefirebase-339fa.firebaseapp.com',
    storageBucket: 'ecommercefirebase-339fa.firebasestorage.app',
    measurementId: 'G-K4JLWH1SVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuxejMKvFov1jPIh_sdV15D1jRVs3YLXU',
    appId: '1:1036042599398:android:bdd2360ba5c524304c7427',
    messagingSenderId: '1036042599398',
    projectId: 'ecommercefirebase-339fa',
    storageBucket: 'ecommercefirebase-339fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy9naBXftqQH9_v4Vjwi9byuHeB95qnwg',
    appId: '1:1036042599398:ios:897455fc843900f34c7427',
    messagingSenderId: '1036042599398',
    projectId: 'ecommercefirebase-339fa',
    storageBucket: 'ecommercefirebase-339fa.firebasestorage.app',
    iosBundleId: 'com.example.ecommercefirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy9naBXftqQH9_v4Vjwi9byuHeB95qnwg',
    appId: '1:1036042599398:ios:897455fc843900f34c7427',
    messagingSenderId: '1036042599398',
    projectId: 'ecommercefirebase-339fa',
    storageBucket: 'ecommercefirebase-339fa.firebasestorage.app',
    iosBundleId: 'com.example.ecommercefirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzYOzWXWsXRSXnjR5i6Nr_ManXKVBcV8k',
    appId: '1:1036042599398:web:4fad686e0ccd75324c7427',
    messagingSenderId: '1036042599398',
    projectId: 'ecommercefirebase-339fa',
    authDomain: 'ecommercefirebase-339fa.firebaseapp.com',
    storageBucket: 'ecommercefirebase-339fa.firebasestorage.app',
    measurementId: 'G-9RDFM368E0',
  );
}
